# Generated by Django 3.2.4 on 2021-07-31 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20210729_1937'),
        ('authapp', '0005_alter_shopuser_activation_key_expires'),
    ]

    operations = [
    ]
